language: php

dist: xenial

services:
  - mysql
  - postgresql

env:
  global:
    - COMPOSER_ROOT_VERSION=2.x-dev
    - RECIPE_CORE_VERSION: 4.x-dev

matrix:
  include:
    - php: 7.1
      env: DB=MYSQL PHPUNIT_TEST=1 RECIPE_CORE_VERSION=~4.4.0 COMPOSER_ARG=--prefer-lowest
    - php: 7.3
      env: DB=PGSQL PHPUNIT_TEST=1
    - php: 7.4
      env: DB=MYSQL PHPUNIT_TEST=1 PHPCS_TEST=1
    - php: nightly
      env: DB=MYSQL PHPUNIT_TEST=1 COMPOSER_ARG=--ignore-platform-reqs
    - php: 7.4
      env: DB=MYSQL PHPUNIT_COVERAGE_TEST=1

before_script:
  # Init PHP
  - phpenv rehash
  - phpenv config-rm xdebug.ini || true

  # Install composer dependencies
  - composer validate
  - if [[ $DB == PGSQL ]]; then composer require --no-update silverstripe/postgresql:^2; fi
  - composer require --no-update silverstripe/recipe-core:$RECIPE_CORE_VERSION
  - composer update $COMPOSER_ARG --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml; fi
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs src/ tests/; fi

after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi
